### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by Devan-Kerman**

### CODE REVIEW

**Comment by jearmstrong21** [comment]
E

**Comment by jearmstrong21** [comment]
in other news

**Comment by jearmstrong21** [comment]
commentspam is the new black

**Comment by jearmstrong21** [comment]
ooh

**Comment by jearmstrong21** [comment]
ur gonna get lots of emails

**Comment by jearmstrong21** [comment]
yeet

**Comment by jearmstrong21** [comment]
enjoy

**Comment by hYdos** [comment]
:concern:

**Pull request closed without merging**
