### PR TITLE
ok

### PR DESCRIPTION
**Pull request by shedaniel**

### CODE REVIEW

**Comment by valoeghese** [comment]
this pr... merely.... deletes files

**Comment by Devan-Kerman** [comment]
what

**Comment by valoeghese** [comment]
this doesn't seem... .to add... anything............

**Comment by Devan-Kerman** [comment]
image
doubt

**Comment by valoeghese** [comment]
did he fake the additions :yotefriccinhaw:

**Comment by ramidzkh** [comment]
he replaced the widener :flushed:

**Comment by valoeghese** [comment]
he literally added nothing according to github

**Comment by valoeghese** [comment]
image
i approve nvm

**Comment by Devan-Kerman** [comment]
blessed

**Pull request merged**
