### PR TITLE
optimize

### PR DESCRIPTION
**Pull request by Devan-Kerman**

### CODE REVIEW

**Comment by Devan-Kerman** [comment]
I have optimized the code

**Comment by Devan-Kerman** [comment]
this is ready to merge

**Comment by Devan-Kerman** [comment]
@valoeghese requesting merge

**Comment by Devan-Kerman** [comment]
from my testing this lead to a 1000% increase in load times, and a 100% increase in mspt

**Comment by Devan-Kerman** [comment]
we're talking about optimizations the likes the world has never seen here

**Comment by redstoneguy12** [comment]
Please stop optimizing things it's supposed to be slow

**Comment by redstoneguy12** [comment]
Nevermind, just read some of it

**Comment by valoeghese** [comment]
that's not even optimisation

**Pull request closed without merging**
